/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IKeenCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenCallee__factory>;
    getContractFactory(
      name: "IKeenERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenERC20__factory>;
    getContractFactory(
      name: "IKeenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenFactory__factory>;
    getContractFactory(
      name: "IKeenPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenPair__factory>;
    getContractFactory(
      name: "KeenERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenERC20__factory>;
    getContractFactory(
      name: "KeenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenFactory__factory>;
    getContractFactory(
      name: "KeenPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenPair__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IKeenCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenCallee__factory>;
    getContractFactory(
      name: "IKeenERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenERC20__factory>;
    getContractFactory(
      name: "IKeenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenFactory__factory>;
    getContractFactory(
      name: "IKeenPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenPair__factory>;
    getContractFactory(
      name: "KeenERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenERC20__factory>;
    getContractFactory(
      name: "KeenPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenPair__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IKeenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenFactory__factory>;
    getContractFactory(
      name: "IKeenPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenPair__factory>;
    getContractFactory(
      name: "IKeenRouter01",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenRouter01__factory>;
    getContractFactory(
      name: "IKeenRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKeenRouter02__factory>;
    getContractFactory(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETH__factory>;
    getContractFactory(
      name: "KeenRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KeenRouter__factory>;
    getContractFactory(
      name: "WBNB",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WBNB__factory>;

    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IKeenCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenCallee>;
    getContractAt(
      name: "IKeenERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenERC20>;
    getContractAt(
      name: "IKeenFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenFactory>;
    getContractAt(
      name: "IKeenPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenPair>;
    getContractAt(
      name: "KeenERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenERC20>;
    getContractAt(
      name: "KeenFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenFactory>;
    getContractAt(
      name: "KeenPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenPair>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IKeenCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenCallee>;
    getContractAt(
      name: "IKeenERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenERC20>;
    getContractAt(
      name: "IKeenFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenFactory>;
    getContractAt(
      name: "IKeenPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenPair>;
    getContractAt(
      name: "KeenERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenERC20>;
    getContractAt(
      name: "KeenPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenPair>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IKeenFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenFactory>;
    getContractAt(
      name: "IKeenPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenPair>;
    getContractAt(
      name: "IKeenRouter01",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenRouter01>;
    getContractAt(
      name: "IKeenRouter02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKeenRouter02>;
    getContractAt(
      name: "IWETH",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETH>;
    getContractAt(
      name: "KeenRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KeenRouter>;
    getContractAt(
      name: "WBNB",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WBNB>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
