/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeenCallee,
  IKeenCalleeInterface,
} from "../../KeenFactory.sol/IKeenCallee";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "keenCall",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKeenCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IKeenCalleeInterface {
    return new utils.Interface(_abi) as IKeenCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeenCallee {
    return new Contract(address, _abi, signerOrProvider) as IKeenCallee;
  }
}
