/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeenConfig,
  IKeenConfigInterface,
} from "../../../contracts/KeenUser.sol/IKeenConfig";

const _abi = [
  {
    inputs: [],
    name: "betInterval",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pair",
        type: "address",
      },
    ],
    name: "betMintFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pair",
        type: "address",
      },
    ],
    name: "betMintMax",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "betReceive",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "betSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBetOdds",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_betOdds",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getInviteRates",
    outputs: [
      {
        internalType: "uint256[]",
        name: "inviteRates",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStackRatios",
    outputs: [
      {
        internalType: "uint256[]",
        name: "stackRatios",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_betInterval",
        type: "uint256",
      },
    ],
    name: "setBetInterval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pair",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_factor",
        type: "uint256",
      },
    ],
    name: "setBetMintFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pair",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_factor",
        type: "uint256",
      },
    ],
    name: "setBetMintMax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_betOdds",
        type: "uint256[]",
      },
    ],
    name: "setBetOdds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_betReceive",
        type: "address",
      },
    ],
    name: "setBetReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_betSender",
        type: "address",
      },
    ],
    name: "setBetSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_inviteRates",
        type: "uint256[]",
      },
    ],
    name: "setInviteRates",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_companyStackRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_committeeStackRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_shareholderStackRatio",
        type: "uint256",
      },
    ],
    name: "setStackRatios",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKeenConfig__factory {
  static readonly abi = _abi;
  static createInterface(): IKeenConfigInterface {
    return new utils.Interface(_abi) as IKeenConfigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeenConfig {
    return new Contract(address, _abi, signerOrProvider) as IKeenConfig;
  }
}
