/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeenUser,
  IKeenUserInterface,
} from "../../../contracts/KeenUser.sol/IKeenUser";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "calculateBetReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_stackType",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "containsStackUser",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_stackType",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "parent",
        type: "address",
      },
    ],
    name: "createStackUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_stackType",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "parent",
        type: "address",
      },
    ],
    name: "deleteStackUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "getParentAddress",
    outputs: [
      {
        internalType: "address",
        name: "parentAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "userInfos",
    outputs: [
      {
        internalType: "address",
        name: "parent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "stackType",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IKeenUser__factory {
  static readonly abi = _abi;
  static createInterface(): IKeenUserInterface {
    return new utils.Interface(_abi) as IKeenUserInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeenUser {
    return new Contract(address, _abi, signerOrProvider) as IKeenUser;
  }
}
