/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TcpPosition,
  TcpPositionInterface,
} from "../../../contracts/KeenUser.sol/TcpPosition";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "getParentAddress",
    outputs: [
      {
        internalType: "address",
        name: "parentAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TcpPosition__factory {
  static readonly abi = _abi;
  static createInterface(): TcpPositionInterface {
    return new utils.Interface(_abi) as TcpPositionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TcpPosition {
    return new Contract(address, _abi, signerOrProvider) as TcpPosition;
  }
}
